export const photoDescriptions = [
  "Cima rocciosa ripresa contro un cielo blu scuro.",
  "Chiesa con guglie illuminate vista tra edifici urbani.",
  "Farfalla nera posata davanti a fette di agrumi.",
  "Fenicotteri in acqua calma durante il giorno.",
  "Tronchi sottili in un bosco autunnale.",
  "Paesaggio innevato con lago ghiacciato e cielo limpido.",
  "Uccello bianco in volo sopra acqua rosata al tramonto.",
  "Paesaggio lacustre velato nella foschia serale.",
  "Branco di cervi nel bosco in luce bassa.",
  "Banchina della metro con treno colorato in arrivo.",
  "Daino in primo piano che guarda verso l'obiettivo.",
  "Daino con palco ripreso in un prato.",
  "Primo piano di un daino tra sfondo sfocato.",
  "Albero solitario davanti a montagne immerse nella nebbia.",
  "Sentiero nel bosco in bianco e nero con panchina.",
  "Piccolo uccello blu appoggiato tra rami e foglie.",
  "Piccolo uccello chiaro posato su un ramo sottile.",
  "Uccello scuro su ramo coperto di licheni.",
  "Uccello nero appoggiato su un tronco tagliato.",
  "Cervo isolato su un pendio erboso.",
  "Cervo adulto con grandi corna in una radura.",
  "Torrente tra rocce ripreso con lunga esposizione.",
  "Cascata stretta tra rocce e muschio.",
  "Piccola cascata in un corso d'acqua roccioso.",
  "Primo piano frontale di un husky.",
  "Grande uccello chiaro con ali aperte.",
  "Luna piena su sfondo nero.",
  "Galleria illuminata con riflessi sul pavimento.",
  "Colonne antiche illuminate di notte.",
  "Strada notturna con luce centrale e cielo verdastro.",
  "Torre su costa rocciosa sotto la Via Lattea.",
  "Farfalla marrone e verde appesa a una foglia.",
  "Farfalla arancione su fiore giallo.",
  "Farfalla con ali arancioni e nere su una foglia.",
  "Piccola farfalla chiara tra rami sottili.",
  "Farfalla nera appoggiata su agrumi tagliati.",
  "Farfalla marrone mimetizzata su una foglia.",
  "Farfalla scura vista dall'alto sopra una ciotola.",
  "Farfalla maculata posata su una tazza colorata.",
  "Giraffe tra gli alberi in un parco.",
  "Tartaruga marina sott'acqua in acqua turchese.",
  "Piccolo gufo nascosto tra i rami.",
  "Lemure ripreso tra foglie e rami.",
  "Elefanti che camminano all'aperto.",
  "Zebra che attraversa uno spazio sabbioso.",
  "Medusa illuminata in acqua blu.",
  "Medusa chiara in acqua blu.",
  "Medusa con lunghi tentacoli su sfondo blu.",
  "Tartaruga marina che nuota vista dall'alto.",
  "Cascata e prato verde ai piedi della roccia.",
  "Cigno rannicchiato sulla riva vicino all'acqua.",
  "Collo di cigno piegato in primo piano.",
  "Cigno che avanza su acqua calma.",
  "Piccolo uccello grigio posato su un ramo.",
  "Uccello nascosto tra rami secchi.",
  "Fenicottero in acqua con una zampa alzata.",
  "Fenicottero in piedi con riflesso nell'acqua.",
  "Fenicottero piegato in avanti nell'acqua.",
  "Renna con finimenti in un paesaggio innevato.",
  "Due renne in primo piano sulla neve.",
  "Primo piano di renna con corna e finimenti.",
  "Renna in movimento su neve e alberi.",
  "Casa rossa sulla neve al crepuscolo.",
  "Cabina telefonica rossa in un bosco innevato.",
  "Galleria rocciosa illuminata con strada riflessa.",
  "Vicolo cittadino illuminato di sera.",
  "Casa chiara in un paesaggio invernale.",
  "Chiesa rossa tra gli alberi.",
  "Persone lontane su una distesa ghiacciata.",
  "Banchina della metro quasi vuota.",
  "Casetta con portico bianco.",
  "Alberi spogli in un bosco autunnale.",
  "Persona sulla banchina sotto un grande orologio.",
  "Uccello appollaiato tra rami spogli.",
  "Cascata tra alberi autunnali.",
  "Sole al tramonto sul mare.",
  "Prato aperto con alberi sullo sfondo.",
  "Uccello in volo vicino a rami bassi.",
  "Montagna innevata in bianco e nero.",
  "Sentiero nel bosco in bianco e nero.",
  "Specchio d'acqua al tramonto con uccelli lontani.",
  "Cervo frontale nel bosco scuro.",
  "Raggi di luce che scendono tra le montagne.",
  "Anatra in atterraggio sull'acqua dorata.",
  "Strada vuota in notturna con bagliore all'orizzonte.",
  "Cascata alta tra rocce chiare.",
  "Primo piano di cigno con becco arancione.",
  "Volto di cigno in primo piano.",
  "Uccello tra rami contro cielo azzurro.",
  "Rapace in volo su cielo pulito.",
  "Uccello lontano in volo nel cielo.",
  "Uccello appollaiato in silhouette sopra un albero.",
  "Uccello in volo ripreso da lontano.",
  "Uccello scuro con ali aperte tra foglie.",
  "Due uccelli in volo sul lago.",
  "Paesaggio lacustre con canneto dorato.",
  "Uccello in volo con montagne sullo sfondo.",
  "Uccello in volo basso con montagne lontane.",
  "Uccello in volo frontale sopra il lago.",
  "Uccello bianco in volo radente.",
  "Stormo lontano nella foschia del mattino.",
  "Due uccelli in volo al tramonto.",
  "Piccolo uccello colorato posato su un palo.",
  "Airone bianco tra gli alberi.",
] as const;
